githubConfigUrl: "https://github.com/dvystrcil/stable-diffution-webui-rcom/"
runnerScaleSetName: "stable-diffution-webui-rcom-runner"
minRunners: 0
maxRunners: 3

template:
  spec:
    volumes:
    - name: harbor-creds
      secret:
        secretName: sd-runner-harbor-pull
        items:
        - key: .dockerconfigjson
          path: config.json
    containers:
    - name: runner
      volumeMounts:
      - name: harbor-creds
        mountPath: /root/.docker/config.json
        subPath: config.json
        readOnly: true
