githubConfigUrl: "https://github.com/dvystrcil/stable-diffution-webui-rcom/"
runnerScaleSetName: "stable-diffution-webui-rcom-runner"
minRunners: 0
maxRunners: 3

template:
  spec:
    volumes:
    - name: harbor-creds
      secret:
        secretName: sd-runner-harbor-pull
    - name: docker-config
      emptyDir: {}
    initContainers:
    - name: setup-docker-config
      image: busybox
      command:
      - sh
      - -c
      - mkdir -p /root/.docker && cp /harbor-creds/.dockerconfigjson /root/.docker/config.json
      volumeMounts:
      - name: harbor-creds
        mountPath: /harbor-creds
      - name: docker-config
        mountPath: /root/.docker
    containers:
    - name: runner
      volumeMounts:
      - name: docker-config
        mountPath: /root/.docker
