apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-internal-ca
  namespace: arc-runner
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDJTCCAg2gAwIBAgIQdkr0YoFiihNYiTBcHIvhwzANBgkqhkiG9w0BAQsFADAd
    MRswGQYDVQQDExJoYXJib3ItaW50ZXJuYWwtY2EwHhcNMjYwNDI4MTUwMjAxWhcN
    MjcwNDI4MTUwMjAxWjAdMRswGQYDVQQDExJoYXJib3ItaW50ZXJuYWwtY2EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDW00oZN8KpZRTWJoG1kqXLsO0n
    ISUQzGLUAdrSYIU5DhyNC7PHk396awiAJMBW7/tP5EiotZDao/ASqTyfPT1KVD5D
    QdfywVR1/EUFuIb8ppuytD7ceGZLcqx1HuMxggdCsIrWsoDYC3WDOaBYIhSXBtAM
    tXSHsNjnT5dmGzWYSryS85hal6+Q5s5HnFeycOVQByj9ApMZgCCI6iDvxBsdjtfE
    DRIAx2s1jdu3Wb7B4mNyS0zbombwj2+qfUacGd4ZlOLCZRU++AgX1DJHthKCFCVO
    7NE90W1WolDnIY5TRIUH50ZsL0r8RYNLyjG58Lk5nhvo+ZlpWX/zfub5IEmzAgMB
    AAGjYTBfMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
    BQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUyssjTKbfiz8ZPOAANc8k
    CtrsPL8wDQYJKoZIhvcNAQELBQADggEBAM/i7oJfjy6AaemYkTc9kvWEgX6WRyD0
    Pc3yX7sgFVHJyrqyxPXoBmz6ncMLCSMoesCX8On/SJz7BqBUVGVNwdyt2IEmxY7p
    rDbLXsRwgvvbkLhc1nMGtIc9JzY8PqTo5/ZlH0sOuB+3YPhw72xDjEOy5oQyKjks
    Wr5Ko67YPrgCDEaA6dQpKlf2QkhzdCtF9wR3qhMecygkm6y9KZmahpldXXskpmeF
    SkQOETmXHmVdNKaGn1TnvIReyyV3rPahI35b3eTuent2RvFLvK8u2Kj/Syb/wZHf
    yBXoX6yw+IoRbeS7CA5mGSRFr/O8pacVJkCvfFAaKWfWLifGp9EYZnE=
    -----END CERTIFICATE-----
