apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-internal-ca
  namespace: arc-runner
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKTCCAhGgAwIBAgIUGTumsRsH62spr5VtOvc4KKzyW/kwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAxMSaGFyYm9yLWludGVybmFsLWNhMB4XDTI2MDQyODE2MDgx
    MFoXDTI2MDcyNzE2MDgxMFowHTEbMBkGA1UEAxMSaGFyYm9yLWludGVybmFsLWNh
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1lbwWUp46t8+GhgFHQzz
    oy5rr2EOmR/Ejs5C7HHnImEULEGsUSIUnBWixxub3v4Hu8NUg5CZGrf6ffudJwUU
    wUJ9JrVI/AK4KuoTdvCn1EHVJY6PvNSaxvGtmLCR23rn+9/UDhkcTx87yJJs5zNf
    IN3n+ZlO7MAD5GTM8knYCqd+y6hCPyyAOS9qfN4C9QTP/BAXGOfu/5EQMgqHU1uH
    z83XhehaEEVJrTtoHQ/Gb91w8UJt2ncqozOaJtzuudU6jMwVmmjsbScWLOIYYYdM
    V5QEyEEJalHB/M0yCnIExaARB+8BJ+P7kz855rZWZlositrQ1dIPOld/1cwG+RMG
    PwIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HQ4EFgQUyhZqtnvALOSW1K9oYHhZUYD3tcAwHQYDVR0RBBYwFIISaGFyYm9yLWlu
    dGVybmFsLWNhMA0GCSqGSIb3DQEBCwUAA4IBAQBTwGXpKe794pULj/KM+YuRrvMv
    UgXiamewLeENQcwrOIhYWmyqeAcl2Ul2XXjnoa8iEJD9+uN7WoCarhJt0SeVEUaC
    tiCM9oBECl7iloXGWIkmav5wB8HNCkWD8dPMILU3N5Bh67o5H62sEn8PcRtAy7n0
    Zw6J7VAzqU9T1Wy9e/MqYu3vGRfYrPsbOS362rSwHGMG979pU1yh8Q1Q+kCx2v3/
    QjDVNAECW/lxeR8Yrg/8F4C7Az1PTZySA1jduM7eFBgqIcLFm6FKSjqkcaUAIArf
    QjW7nu8PYvt4q2Ayyh0bm6udab6b2xQN0HARiinU+ofe+9BWf1n8ll7howUC
    -----END CERTIFICATE-----
