apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: sd-runner-infisical-secret
  namespace: arc-runner
spec:
  hostAPI: https://infisical.sirddail.net/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-bz-gt
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
  - secretName: sd-runner-harbor-pull
    secretNamespace: arc-runner
    secretType: kubernetes.io/dockerconfigjson
    creationPolicy: "Orphan"
    template:
      includeAllSecrets: false
      data:
        ".dockerconfigjson": '{"auths":{"{{ .HB_REGISTRY.Value }}":{"username":"{{ .HB_USERNAME.Value }}","password":"{{ .HB_PASSWORD.Value }}","auth":"{{ .HB_AUTH.Value }}"},"harbor-core.harbor.svc.cluster.local":{"username":"{{ .HB_USERNAME.Value }}","password":"{{ .HB_PASSWORD.Value }}","auth":"{{ .HB_AUTH.Value }}"}}}'
