apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-webui-rcom
  labels:
    app: sd-webui-rcom
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-webui-rcom
  template:
    metadata:
      labels:
        app: sd-webui-rcom
    spec:
      tolerations:
        - key: "ollama"
          operator: "Equal"
          value: "yes"
          effect: "NoSchedule"
      containers:
      - name: sd-webui-rcom
        image: ghcr.io/dvystrcil/stable-diffution-webui-rcom:main
        ports:
        - containerPort: 7860
        env:
        - name: COMMANDLINE_ARGS
          value: "--listen --port 7860"
        # resources:
        #   # requests:
        #   #   memory: "4Gi"
        #   #   cpu: "1000m"            
        #   limits:
        #     # memory: "8Gi"
        #     # cpu: "2000m"
        #     amd.com/gpu: 1
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
        volumeMounts:
          - name: venv
            mountPath: '/app/venv'
      #   # - name: ollama-claim
      #   #   mountPath: /root/.ollama
      #   - mountPath: /dev/kfd
      #     name: kfd
      #   - mountPath: /dev/dri
      #     name: dri
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: venv
          emptyDir: {}
      # - name: kfd
      #   hostPath:
      #     path: /dev/kfd
      # - name: dri
      #   hostPath:
      #     path: /dev/dri
---
apiVersion: v1
kind: Service
metadata:
  name: sd-webui-rcom
spec:
  selector:
    app: sd-webui-rcom
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7860
  type: ClusterIP

